config/routes.rb
Rails.application.routes.draw do
  get '/chessboard', to: 'chessboard#chessboard'
  devise_for :users
  root to: "creatives#index"
  resources :welcome
  mount ActionCable.server => "/cable"
  post :upvote, to: 'votes#upvote'
  post :downvote, to: 'votes#downvote'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game
  def self.start(uuid1, uuid2)
    white, black = [uuid1, uuid2].shuffle

    ActionCable.server.broadcast "player_#{white}", {action: "game_start", msg: "white"}
    ActionCable.server.broadcast "player_#{black}", {action: "game_start", msg: "black"}

    REDIS.set("opponent_for:#{white}", black)
    REDIS.set("opponent_for:#{black}", white)
  end

  def self.forfeit(uuid)
    if winner = opponent_for(uuid)
      ActionCable.server.broadcast "player_#{winner}", {action: "opponent_forfeits"}
    end
  end

  def self.opponent_for(uuid)
    REDIS.get("opponent_for:#{uuid}")
  end

  def self.make_move(uuid, data)
    opponent = opponent_for(uuid)
    move_string = "#{data["from"]}-#{data["to"]}"
    ActionCable.server.broadcast "player_#{opponent}", {action: "make_move", msg: move_string}
  end
end

app/models/seek.rb
class Seek
  def self.create(uuid)
    if opponent = REDIS.spop("seeks")
      Game.start(uuid, opponent)
    else
      REDIS.sadd("seeks", uuid)
    end
  end

  def self.remove(uuid)
    REDIS.srem("seeks", uuid)
  end

  def self.clear_all
    REDIS.del("seeks")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :votes
  
  def total_votes
    votes.pluck(:value).sum
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # before_action :authenticate_user!
end

app/controllers/chessboard_controller.rb
class ChessboardController < ApplicationController
	def chessboard
	end
end

app/controllers/creatives_controller.rb
class CreativesController < ApplicationController
  layout "creative"

  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chessboard/chessboard.html.erb
<%= javascript_include_tag 'chessboard', 'data-turbolinks-track': 'reload' %>
<%= render 'partials/navbargames' %>
<div id="board"></div>
</br>
</br>
</br>
<p> Moves log: </p>
<div id="pgn"> </div>

app/views/creatives/_bg_primary.html.erb
<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Chess :D What is IT?</h2>
                <hr class="light">
                <p class="text-faded">Chess is a two-player strategy board game played on a chessboard, a checkered gameboard with 64 squares arranged in an eight-by-eight grid.[1] Chess is played by millions of people worldwide, both amateurs and professionals.</p>
                <a href="#services" class="btn btn-default btn-xl page-scroll">Get Started!</a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_call_to_action.html.erb
<aside class="bg-dark">
    <div class="container text-center">
        <div class="call-to-action">
            <h2>Free Game Test</h2>
            <% if user_signed_in? %>
              <a href="/welcome" class="btn btn-default btn-xl wow tada">Vs Player</a>
            <% else %>
              <a href="/users/sign_in" class="btn btn-default btn-xl wow tada">Vs Player</a>
            <% end %>
            <a href="/chessboard" class="btn btn-default btn-xl wow tada">Vs Computer</a>
        </div>
    </div>
</aside>

app/views/creatives/_contact.html.erb
<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 text-center">
                <h2 class="section-heading">Let's Get In the CHESSZONE!</h2>
                <hr class="primary">
                <p>Interested in getting the game for your own? Give us a call or send us an email and we will get back to you as soon as possible!</p>
            </div>
            <div class="col-lg-4 col-lg-offset-2 text-center">
                <%= image_tag "creative/phone-call.png", class: "wow bounceIn" , alt: "" %>
                <p>013-5932043</p>
            </div>
            <div class="col-lg-4 text-center">
                <%= image_tag "creative/envelope.png", class: "wow bounceIn" , alt: "" %>
                <p><a href="mailto:your-email@your-domain.com">chezz@chezz.com</a></p>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_header.html.erb
<header>
    <div class="header-content">
        <div class="header-content-inner">
            <h1>CHESS</h1>
            <hr>
            <p>The Game Where Everyone Thinks Too Long</p>
            <a href="#about" class="btn btn-primary btn-xl page-scroll">Find Out More</a>
        </div>
    </div>
</header>

app/views/creatives/_navbar.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">ONLINE CHESS</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
               <% if user_signed_in? %>
                 <a class="page-scroll"> Logged in as <strong><%= current_user.email %></strong></a>
                 <li>
                   <a class="page-scroll" href= /welcome >Play</a>
                 </li>
                 <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
               <% else %>
               <li>
                 <a class="page-scroll" href= /users/sign_up >Register</a>
               </li>
               <li>
                 <a class="page-scroll" href= /users/sign_in >Login</a>
               </li>
               <% end %>


                <li>
                    <a class="page-scroll" href="#about">About</a>
                </li>
                <li>
                    <a class="page-scroll" href="#services">Army</a>
                </li>
                <li>
                    <a class="page-scroll" href="#portfolio">Chess Wonders</a>
                </li>
                <li>
                    <a class="page-scroll" href="#contact">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/creatives/_portfolio.html.erb
<section class="no-padding" id="portfolio">
    <div class="container-fluid">
        <div class="row no-gutter">
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/1.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/2.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/3.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/4.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/5.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-lg-4 col-sm-6">
                <a href="#" class="portfolio-box">
                    <%= image_tag "creative/6.jpg", class: "img-responsive", alt: "" %>
                    <div class="portfolio-box-caption">
                        <div class="portfolio-box-caption-content">
                            <div class="project-category text-faded">
                                Category
                            </div>
                            <div class="project-name">
                                Project Name
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</section>

app/views/creatives/_services.html.erb
<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">MEET YOUR ARMY</h2>
                <hr class="primary">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <%= image_tag "creative/pawn.png", class: "img-responsive", alt: "" %>
                    <h3>PAWN</h3>
                    <p class="text-muted">Unlike other pieces, pawns may not move backwards. Normally a pawn moves by advancing a single square, but the first time a pawn is moved, it has the option of advancing two squares. Pawns may not use the initial two-square advance to jump over an occupied square, or to capture. Any piece directly in front of a pawn, friend or foe, blocks its advance.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <%= image_tag "creative/chess-knight.png", class: "img-responsive", alt: "" %>
                    <h3>KNIGHT</h3>
                    <p class="text-muted">The knight move is unusual among chess pieces. When it moves, it can move to a square that is two squares horizontally and one square vertically, or two squares vertically and one square horizontally. The complete move therefore looks like the letter L. Unlike all other standard chess pieces, the knight can 'jump over' all other pieces (of either color) to its destination square. It captures an enemy piece by replacing it on its square.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <%= image_tag "creative/rook.png", class: "img-responsive", alt: "" %>
                    <h3>ROOK</h3>
                    <p class="text-muted">The rook moves horizontally or vertically, through any number of unoccupied squares. As with captures by other pieces, the rook captures by occupying the square on which the enemy piece sits.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <%= image_tag "creative/bishop.png", class: "img-responsive", alt: "" %>
                    <h3>BISHOP</h3>
                    <p class="text-muted">The bishop has no restrictions in distance for each move, but is limited to diagonal movement. Bishops, like all other pieces except the knight, cannot jump over other pieces. A bishop captures by occupying the square on which an enemy piece sits.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <%= image_tag "creative/queen.png", class: "img-responsive", alt: "" %>
                    <h3>QUEEN</h3>
                    <p class="text-muted">The queen can be moved any number of unoccupied squares in a straight line vertically, horizontally, or diagonally, thus combining the moves of the rook and bishop. The queen captures by occupying the square on which an enemy piece sits.</p>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box">
                    <%= image_tag "creative/chess-king.png", class: "img-responsive", alt: "" %>
                    <h3>KING</h3>
                    <p class="text-muted">A king can move one square in any direction (horizontally, vertically, or diagonally) unless the square is already occupied by a friendly piece or the move would place the king in check</p>
                </div>
            </div>

        </div>
    </div>
</section>

app/views/creatives/index.html.erb
<% if notice %>
  <p class="alert alert-success text-center"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger text-center"><%= alert %></p>
<% end %>
<%= render 'navbar' %>
<%= render 'header' %>
<%= render 'bg_primary' %>
<%= render 'services' %>
<%= render 'portfolio' %>
<%= render 'call_to_action' %>
<%= render 'contact' %>

app/views/landing/index.html.erb
<!DOCTYPE html>
<html>

  <head>

    <title>Rails 5 Chess</title>
    <%= csrf_meta_tags %>
    
  </head>

  <body>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'play', welcome_index_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
    <% else %>
      <p4> Please
      <%= link_to "Sign up", new_user_registration_path  %>
      or
      <%= link_to "Login", new_user_session_path %>
      to play
    </p4>
    <% end %>


    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>

    <title>Rails 5 Chess</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/creative.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Chezz Chess </title>
  <%= stylesheet_link_tag 'creative/manifest.css', media: 'all' %>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'creative/manifest.js' %>
  <%= csrf_meta_tags %>
</head>

<body>

<%= yield %>

</body>
</html>

app/views/partials/_navbargames.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand page-scroll" href=/ >ONLINE CHESS</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
               <% if user_signed_in? %>
                 <li>
                   <a class="page-scroll"> Logged in as <strong><%= current_user.email %></strong></a>
                 </li>
                 <li>
                   <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
                 </li>
               <% else %>
               <li>
                 <a class="page-scroll" href= /users/sign_up >Register</a>
               </li>
               <li>
                 <a class="page-scroll" href= /users/sign_in >Login</a>
               </li>
               <% end %>

            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<%= javascript_include_tag 'index', 'data-turbolinks-track' => true %>
<%= render 'partials/navbargames' %>

<div id="chessboard" style="width: 400px"></div>
</br>
</br>
</br>
</br>
<div id="messages"></div>